[character]      # The name of the module we are confguring is "character"
symbol = "❯"

[git_branch]
symbol = " "

[package]
symbol = " "

[python]

[time]
disabled = false
format = "%T"
utc_time_offset = -5
