require('keymaps')
require('load_lazy')
-- require('plugins.treesitter')
-- require('plugins.complete')
-- require('plugins.lsp')
-- require('plugins.tele')
-- require('plugins.other')
-- require('plugins.git')
require('options')
